# Site settings
title: Bottreypich [Cassey] Chap
description: BCChap's Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://bcchap.github.io/tester/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bottreypich [Cassey] Chap
user_title: Data Wrangler
email: bcchap@ucdavis.edu
github_username:  bcchap

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
