# Site settings
title: Bottreypich [Cassey] Chap
description: BCChap's Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bottreypich [Cassey] Chap
user_description: University of California, Davis | Class of 2021 | Physics (Geophysics & Particle)
user_title: Data Wrangler | Community Advocate
email: bcchap@ucdavis.edu
#twitter_username: lorem_ipsum
github_username:  bcchap
#gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'node_modules']
